### ISSUE TITLE
导航条会瞬间消失

### ISSUE THREAD

**Issue by livv** [EnderTan/ETNavBarTransparent#1]
![untitled](https://cloud.githubusercontent.com/assets/792973/23784777/eded9570-059e-11e7-91e5-c10352171434.gif)

在首页第一次点击push， 导航条会瞬间消失，然后执行过渡动画。点击back按钮，也是如此。这里导航条没有过渡动画，请问怎么破？  我看支付宝里做的效果还不错。

**Comment by EnderTan** [comment]
![fadepush](https://cloud.githubusercontent.com/assets/6407503/23787181/c4774a12-05ab-11e7-9348-df361645d07b.gif)
因为push动画只有0.35s，在视觉残留的影响下，加上Fade动画反而有点奇怪，所以先去掉了。找到合适的方案后我会再更新。
