### ISSUE TITLE
替换私有API

### ISSUE THREAD

**Issue by huangboju** [EnderTan/ETNavBarTransparent#11]
可以不用那个私有API，直接监听手势
http://www.jianshu.com/p/dd2137c63b3e

**Comment by EnderTan** [comment]
谢谢提醒。最开始是用手势监听实现的，但因为原项目有较复杂的手势交互，有几个自定义手势都会触发返回，所以就统一用一个系统的方法监听了。事实证明，苹果对这种私有接口的使用一般是不会管的，起码我的两个APP都没有这方面的警告。
但考虑到绝大部分项目都只有系统返回手势或最多加个全屏返回，所以后面应该会去掉私有接口，或提供选择。
