### ISSUE TITLE
我用pod导进来有报错，要怎么改？

### ISSUE THREAD

**Issue by bighansen** [EnderTan/ETNavBarTransparent#21]
let originalMethod = class_getInstanceMethod(self, selector)
let swizzledMethod = class_getInstanceMethod(self, Selector(str))
method_exchangeImplementations(originalMethod, swizzledMethod)
这句话有错误。

**Comment by TimorCan** [comment]
me too

**Comment by hydyy** [comment]
把环境改成 swift3 就可以了，楼主代码并没有支持4

**Comment by TimorCan** [comment]
我直接guard改了下就可以了，也没影响使用，就是这个方法可能报空

**Comment by TimorCan** [comment]
guard let swizzledMethod = class_getInstanceMethod(self, Selector(str)) else {return}

**Comment by EnderTan** [comment]
Has been updated to Swift4
