### ISSUE TITLE
10.3系统导航栏无法透明

### ISSUE THREAD

**Issue by MysteryRan** [EnderTan/ETNavBarTransparent#26]
![file-read-196](https://user-images.githubusercontent.com/17866688/41642034-c0f98216-7499-11e8-9fdd-a82ced660347.jpg)

**Comment by MysteryRan** [comment]
alpha=1

**Comment by MysteryRan** [comment]
isTranslucent 影响

**Comment by EnderTan** [comment]
已经是隐藏的，只是navigationBar.isTranslucent设置为true时，视图控制器会自动把view的top设置为64，你看到的黑色是最底层window的颜色。
解决方法是你自己布局好你的View，或设置成navigationBar.isTranslucent = true
