### ISSUE TITLE
模态弹出navigationcontroller时Crash

### ISSUE THREAD

**Issue by liufengting** [EnderTan/ETNavBarTransparent#28]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/4414522/42499549-a7290d8e-8461-11e8-803e-07d057a81761.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/4414522/42499562-af796c2c-8461-11e8-9405-8fa780261f73.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/4414522/42499602-c76fa2a6-8461-11e8-9c43-3c1031dcc717.png">

复现步骤：

1. 新建工程，pod 'ETNavBarTransparent' ， install
2. 模态弹出navigationcontroller（图一），导航栏self.navBarBgAlpha = 0;（图二）
3. 弹出时crash（图三）。

帮忙抽空看一下这个问题

**Comment by liufengting** [comment]
@EnderTan

**Comment by EnderTan** [comment]
@liufengting I can't reproduce your Crash by following the steps. Check if you are using the latest version, or upload the full project and I will check what's wrong.

**Comment by EnderTan** [comment]
@liufengting and provide your iOS version please?

**Comment by liufengting** [comment]
@EnderTan I tried the same code in Xcode 9, it works fine. But in Xcode 10.0 beta 3 (10L201y), it crashed. Sorry for the trouble.
