### ISSUE TITLE
我想知道这段代码的意义！

### ISSUE THREAD

**Issue by hanleiZoro** [EnderTan/ETNavBarTransparent#29]
<img width="996" alt="2018-07-26 7 07 06" src="https://user-images.githubusercontent.com/38712031/43258927-27bfc134-9107-11e8-9038-b0a62a7dc18c.png">

这段代码崩溃了。 数组越界。 是否是我弄错了什么！

**Comment by JarryT** [comment]
just check out the viewController.count and n , see if n is <= viewController.count - 1
