### ISSUE TITLE
iOS12 UINavigationController(rootViewController:ViewController()) 报空数组越界错误

### ISSUE THREAD

**Issue by weiweilong** [EnderTan/ETNavBarTransparent#30]
作者你好，使用了ETNavBarTransparent确实很方便，也很好用，但是最近跑iOS12设备的时候，初始化导航控制器时UINavigationController(rootViewController:ViewController())，报空数组越界错误 “[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray”。麻烦您抽时间维护一下，谢谢。

**Comment by EnderTan** [comment]
已修复，Thanks~
