### ISSUE TITLE
Extra argument in call

### ISSUE THREAD

**Issue by JiaLiangoooo** [EnderTan/ETNavBarTransparent#5]
get {
            let alpha = objc_getAssociatedObject(self, &AssociatedKeys.navBarBgAlpha) as? CGFloat
            if alpha == nil {
                return 1.0
            }else{
                return alpha!
            }
            let alpha1 = objc_getAssociatedObject(self, &AssociatedKeys.navBarBgAlpha) //在这里会报错 Extra argument in call (在下面那个也会这样)
            
        }
        set {
            var alpha = newValue
            if alpha > 1 {
                alpha = 1
            }
            if alpha < 0 {
                alpha = 0
            }
            
            objc_setAssociatedObject(self, &AssociatedKeys.navBarBgAlpha, alpha, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) //在这里会报错 Extra argument in call (在下面那个也会这样)

我拖到我另一个项目中不会发生这个问题 但是在这个项目会报这种错

**Comment by yinjialiang1993** [comment]
`    open var navBarBgAlpha: CGFloat {
        get {
            let alpha = objc_getAssociatedObject(self, &AssociatedKeys.navBarBgAlpha) as? CGFloat
            if alpha == nil {
                return 1.0
            }else{
                return alpha!
            }
            let alpha1 = objc_getAssociatedObject(self, &AssociatedKeys.navBarBgAlpha) //Extra argument in call
            
        }
        set {
            var alpha = newValue
            if alpha > 1 {
                alpha = 1
            }
            if alpha < 0 {
                alpha = 0
            }
            
            objc_setAssociatedObject(self, &AssociatedKeys.navBarBgAlpha, alpha, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) //Extra argument in call
            
            //Update UI
            navigationController?.setNeedsNavigationBackground(alpha: alpha)
        }
    }
`
