### ISSUE TITLE
有一个效果细节问题

### ISSUE THREAD

**Issue by cooliean** [EnderTan/ETNavBarTransparent#6]
<img width="466" alt="qq20170317-150859 2x" src="https://cloud.githubusercontent.com/assets/4754617/24032566/ae2b1112-0b23-11e7-8e3a-828abd7ddd67.png">

就是如上图，我想下拉的时候的回弹空间背景是橙色，但是我很多时候，我下面的数据只有一两条。不不会是很多的。因为现在背景是设在TableView上的，所以就出现了上图的效果了。如果不设置背景色也不行，不设置的话，那么下拉的时候，就会有白色，不连续的效果，不好看。
tableView.tableFooterView = UIView();这个方式也不行。

**Comment by EnderTan** [comment]
把headerView设为不裁剪subView，滚动时调整subView的frame(上部超出headerView)，就能实现你说的效果了。这里设置背景色只是不想demo加入与主题不相关的代码。
