### ISSUE TITLE
UIImagePickerController issue 

### ISSUE THREAD

**Issue by terflogag** [EnderTan/ETNavBarTransparent#7]
Hello,

Since I added `ETNavbarTransparent` my `UIImagePickerController` doesn't work (`UIImagePickerControllerDelegate` function are never performed). There is any chance of this issue came from the `UINavigationControllerDelegate` extension used in `ETNavbarTransparent` (which are also used for UIImagePickerController) ?

Thank you

**Comment by EnderTan** [comment]
This problem has been solved, please check out the new version. Thanks for your issue
